"""
logging/agent_logger.py
Writes structured start/end/fail/skip records to the agent_logs table.

TTL rules (set at INSERT time — never rely on pg_cron):
  success / skipped  → expires_at = NOW() + 3 days
  failed             → expires_at = NOW() + 30 days

run_id: UUID generated by each agent at the top of its function.
        Shared between log_start and log_end/log_fail for correlation.
"""

from datetime import datetime, timezone, timedelta
from typing import Optional
import uuid

from db.client import get_supabase


# Public Name Mapping (March 16 Branding Alignment)
AGENT_PUBLIC_NAMES = {
    "agent3_resume":       "Parichay",
    "agent4_skill_gap":    "Kaushal",
    "agent5_career_intel": "Niti",
    "agent6_fit":          "Yogya",
    "agent7_jd":           "Sarthis",
    "agent8_coach":        "Guru",
    "agent10_tailor":      "Shilpakaar",
    "agent11_cover_letter": "Prerna",
    "agent12_applier":     "Setu",
    "agent13_anti_ban":    "Sarthis",
    "agent14_follow_up":   "Anuvartan",
    "agent15_calibrator":  "Sarthis",
    "upload_security":     "Sarthis",
}

def _now() -> datetime:
    return datetime.now(timezone.utc)


async def log_start(
    agent_name: str,
    user_id: Optional[str],
    run_id: str,
) -> None:
    """Insert an agent_logs row with status='started'."""
    display_name = AGENT_PUBLIC_NAMES.get(agent_name, agent_name)
    get_supabase().table("agent_logs").insert({
        "id":           run_id,
        "agent_name":   agent_name,
        "display_name": display_name,
        "user_id":      user_id,
        "status":       "started",
        "started_at":   _now().isoformat(),
        "expires_at":   (_now() + timedelta(days=3)).isoformat(),
    }).execute()


async def log_end(
    run_id: str,
    records_processed: int,
    duration_ms: int,
) -> None:
    """Update agent_logs row to status='completed'."""
    get_supabase().table("agent_logs").update({
        "status":             "completed",
        "records_processed":  records_processed,
        "duration_ms":        duration_ms,
        "completed_at":       _now().isoformat(),
        "expires_at":         (_now() + timedelta(days=3)).isoformat(),
    }).eq("id", run_id).execute()


async def log_fail(
    run_id: str,
    error: str,
    duration_ms: int,
) -> None:
    """Update agent_logs row to status='failed' with 30-day TTL."""
    get_supabase().table("agent_logs").update({
        "status":        "failed",
        "error_message": error[:500],   # cap length — never log full stack with secrets
        "duration_ms":   duration_ms,
        "completed_at":  _now().isoformat(),
        "expires_at":    (_now() + timedelta(days=30)).isoformat(),
    }).eq("id", run_id).execute()


async def log_skip(
    run_id: str,
    reason: str,
) -> None:
    """Update agent_logs row to status='skipped'."""
    get_supabase().table("agent_logs").update({
        "status":        "skipped",
        "error_message": reason[:500],
        "completed_at":  _now().isoformat(),
        "expires_at":    (_now() + timedelta(days=3)).isoformat(),
    }).eq("id", run_id).execute()


def new_run_id() -> str:
    """Generate a fresh UUID for a new agent run."""
    return str(uuid.uuid4())


async def log_event(
    agent_name: str,
    level: str,
    message: str,
    user_id: Optional[str] = None,
) -> None:
    """
    Insert a generic event log (e.g. warning, error) with a fresh run_id.
    Used for events that don't follow the full start/end lifecycle.
    """
    run_id = new_run_id()
    display_name = AGENT_PUBLIC_NAMES.get(agent_name, agent_name)

    # TTL: warnings/errors 30 days, others 3 days
    ttl_days = 30 if level in ["warn", "error", "failed"] else 3

    get_supabase().table("agent_logs").insert({
        "id":            run_id,
        "agent_name":    agent_name,
        "display_name":  display_name,
        "user_id":       user_id,
        "status":        level,
        "error_message": message[:500],
        "started_at":    _now().isoformat(),
        "completed_at":  _now().isoformat(),
        "expires_at":    (_now() + timedelta(days=ttl_days)).isoformat(),
    }).execute()
