"""
logging/agent_logger.py
Writes structured start/end/fail/skip records to the agent_logs table.

TTL rules (set at INSERT time — never rely on pg_cron):
  success / skipped  → expires_at = NOW() + 3 days
  failed             → expires_at = NOW() + 30 days

run_id: UUID generated by each agent at the top of its function.
        Shared between log_start and log_end/log_fail for correlation.
"""

from datetime import datetime, timezone, timedelta
from typing import Optional
import uuid

from db.client import supabase


def _now() -> datetime:
    return datetime.now(timezone.utc)


async def log_start(
    agent_name: str,
    user_id: Optional[str],
    run_id: str,
) -> None:
    """Insert an agent_logs row with status='started'."""
    supabase.table("agent_logs").insert({
        "id":           run_id,
        "agent_name":   agent_name,
        "user_id":      user_id,
        "status":       "started",
        "started_at":   _now().isoformat(),
        "expires_at":   (_now() + timedelta(days=3)).isoformat(),
    }).execute()


async def log_end(
    run_id: str,
    records_processed: int,
    duration_ms: int,
) -> None:
    """Update agent_logs row to status='completed'."""
    supabase.table("agent_logs").update({
        "status":             "completed",
        "records_processed":  records_processed,
        "duration_ms":        duration_ms,
        "completed_at":       _now().isoformat(),
        "expires_at":         (_now() + timedelta(days=3)).isoformat(),
    }).eq("id", run_id).execute()


async def log_fail(
    run_id: str,
    error: str,
    duration_ms: int,
) -> None:
    """Update agent_logs row to status='failed' with 30-day TTL."""
    supabase.table("agent_logs").update({
        "status":        "failed",
        "error_message": error[:500],   # cap length — never log full stack with secrets
        "duration_ms":   duration_ms,
        "completed_at":  _now().isoformat(),
        "expires_at":    (_now() + timedelta(days=30)).isoformat(),
    }).eq("id", run_id).execute()


async def log_skip(
    run_id: str,
    reason: str,
) -> None:
    """Update agent_logs row to status='skipped'."""
    supabase.table("agent_logs").update({
        "status":        "skipped",
        "error_message": reason[:500],
        "completed_at":  _now().isoformat(),
        "expires_at":    (_now() + timedelta(days=3)).isoformat(),
    }).eq("id", run_id).execute()


def new_run_id() -> str:
    """Generate a fresh UUID for a new agent run."""
    return str(uuid.uuid4())
